export const NOTIFICATION_ACTION = {
  REFRESH_NOTIFICATION: "REFRESH_NOTIFICATION",
  REFRESH_NOTIFICATION_FAILED: "REFRESH_NOTIFICATION_FAILED",
  REFRESH_NOTIFICATION_SUCCESS: "REFRESH_NOTIFICATION_SUCCESS",
  GET_MORE_NOTIFICATION: "GET_MORE_NOTIFICATION",
  GET_MORE_NOTIFICATION_FAILED: "GET_MORE_NOTIFICATION_FAILED",
  GET_MORE_NOTIFICATION_SUCCESS: "GET_MORE_NOTIFICATION_SUCCESS",
}
