export enum ESystemRole {
    ADMIN = "Admin",
    USER = "User",
}

export enum UserErrorCode {
    BAD_REQUEST_USER_EXISTED = "BAD_REQUEST_USER_EXISTED",
    BAD_REQUEST_DEVICE_IDENDIFIED = "BAD_REQUEST_DEVICE_IDENDIFIED",
    BAD_REQUEST_WRONG_PASSWORD = "BAD_REQUEST_WRONG_PASSWORD",
    BAD_REQUEST_EMPTY_CLIENT_DEVICE_ID = "BAD_REQUEST_EMPTY_CLIENT_DEVICE_ID",
    BAD_REQUEST_CLIENT_DEVICE_ID_EXIST = "BAD_REQUEST_CLIENT_DEVICE_ID_EXIST",
    BAD_REQUEST_WRONG_OLD_PASSWORD = "BAD_REQUEST_WRONG_OLD_PASSWORD",
    BAD_REQUEST_DUPLICATE_NEW_PASSWORD = "BAD_REQUEST_DUPLICATE_NEW_PASSWORD",
}

export enum EFriendRequest {
    PENDING = "pending",
    ACCEPTED = "accepted",
    REJECTED = "rejected"
}