export enum Platform {
    WEB = "Web",
    MOBILE = "Mobile",
}

export enum AuthErrorCode {
    UNAUTHORIZED_USERNAME_NOT_FOUND = "UNAUTHORIZED_USERNAME_NOT_FOUND",
    UNAUTHORIZED_WRONG_PASSWORD = "UNAUTHORIZED_WRONG_PASSWORD",
    UNAUTHORIZED_WRONG_IDENTIFY_DEVICE = "UNAUTHORIZED_WRONG_IDENTIFY_DEVICE",
    UNAUTHORIZED_WRONG_WORKSPACE_IP_ADDRESS = "UNAUTHORIZED_WRONG_WORKSPACE_IP_ADDRESS",
}